/** @type {import('next').NextConfig} */
const nextConfig = {
  compiler: {
    styledComponents: true,
  },
  images: {
    unoptimized: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  env: {
    NEXT_PUBLIC_VITE_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_VITE_FIREBASE_API_KEY || process.env.VITE_FIREBASE_API_KEY || "",
    NEXT_PUBLIC_VITE_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_VITE_FIREBASE_AUTH_DOMAIN || process.env.VITE_FIREBASE_AUTH_DOMAIN || "",
    NEXT_PUBLIC_VITE_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_VITE_FIREBASE_PROJECT_ID || process.env.VITE_FIREBASE_PROJECT_ID || "",
    NEXT_PUBLIC_VITE_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_VITE_FIREBASE_STORAGE_BUCKET || process.env.VITE_FIREBASE_STORAGE_BUCKET || "",
    NEXT_PUBLIC_VITE_FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_VITE_FIREBASE_MESSAGING_SENDER_ID || process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
    NEXT_PUBLIC_VITE_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_VITE_FIREBASE_APP_ID || process.env.VITE_FIREBASE_APP_ID || "",
    NEXT_PUBLIC_VITE_FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_VITE_FIREBASE_MEASUREMENT_ID || process.env.VITE_FIREBASE_MEASUREMENT_ID || "",
    
    VITE_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_VITE_FIREBASE_API_KEY || process.env.VITE_FIREBASE_API_KEY || "",
    VITE_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_VITE_FIREBASE_AUTH_DOMAIN || process.env.VITE_FIREBASE_AUTH_DOMAIN || "",
    VITE_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_VITE_FIREBASE_PROJECT_ID || process.env.VITE_FIREBASE_PROJECT_ID || "",
    VITE_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_VITE_FIREBASE_STORAGE_BUCKET || process.env.VITE_FIREBASE_STORAGE_BUCKET || "",
    VITE_FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_VITE_FIREBASE_MESSAGING_SENDER_ID || process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
    VITE_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_VITE_FIREBASE_APP_ID || process.env.VITE_FIREBASE_APP_ID || "",
    VITE_FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_VITE_FIREBASE_MEASUREMENT_ID || process.env.VITE_FIREBASE_MEASUREMENT_ID || "",
  },
};

export default nextConfig;
